### ISSUE TITLE
We're lost...

### ISSUE THREAD

**Issue by bianca-prohaska-NOAA** [nmfs-openscapes/2022-noaa-afsc-fall#21]
@meganferg 
@GavinMBrady 

We know how to make **_bulleted lists_**

- one 
- two 
- three

We know how to make check lists

- [x] task 1
- [x] task 2

**Comment by GavinMBrady** [comment]
Less lost. Thanks.

**Comment by stefaniebutland** [comment]
whew!

**Comment by meganferg** [comment]
Now, just wondering how we find out that we've been tagged without having to read through every issue that appears in the list

**Comment by joannamagner-noaa** [comment]
@meganferg if you click "Filters" on the main Issues page, you can select a filter to see ones that mention you. might be other ways to do it, but i just found that by accident right after reading your comment. serendipity!

**Comment by bianca-prohaska-NOAA** [comment]
Awesome, thank you @joannamagner-noaa !

**Comment by bianca-prohaska-NOAA** [comment]
Closing this issue!
