### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MorganArrington-NOAA** [nmfs-openscapes/2022-noaa-afsc-fall#9]
@katie-luxa 
@McGowanDW 

Hi! 

What groups do you both work in?

Have you used issues before?

- [x] Yes
- [x] No

**Comment by McGowanDW** [comment]
MACE... yes, I've used Issues before.

**Comment by katie-luxa** [comment]
I'm with MML and I've never used Issues before. Pretty nifty!
